### ISSUE TITLE
Not work in nodejs 0.12.0

### ISSUE THREAD

**Issue by morontt** [gabrielgrant/node-ember-precompile#36]
:(

<pre>An error occurred while running:                                                                                             
  '/opt/local/bin/node' '/opt/local/bin/ember-precompile' '/var/folders/xb/lqtwc9gs4ns7pyjtvrw2ntxr0000gt/T/input_dir54e4b83b  
  cdb73/_jobseeker-list.hbs' '-f' '/private/var/folders/xb/lqtwc9gs4ns7pyjtvrw2ntxr0000gt/T/output2HB3bF'                      
  Error Output:                                                                                                                
  /opt/local/lib/node_modules/ember-precompile/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:418             
    set nodeName() { throw new core.DOMException();},                                                                          
                 ^                                                                                                             
  SyntaxError: Unexpected token )                                                                                              
      at exports.runInThisContext (vm.js:73:16)                                                                                
      at Module._compile (module.js:443:25)                                                                                    
      at Object.Module._extensions..js (module.js:478:10)                                                                      
      at Module.load (module.js:355:32)                                                                                        
      at Function.Module._load (module.js:310:12)                                                                              
      at Module.require (module.js:365:17)                                                                                     
      at require (module.js:384:17)                                                                                            
      at Object.<anonymous> (/opt/local/lib/node_modules/ember-precompile/node_modules/jquery/node_modules/jsdom/lib/jsdom/le  
  vel2/core.js:1:94)                                                                                                           
      at Module._compile (module.js:460:26)                                                                                    
      at Object.Module._extensions..js (module.js:478:10)                                                                      
  Input:
...</pre>

**Comment by GVRV** [comment]
+1 Experiencing the same issue
